-- Schema for H2 (compatible with PostgreSQL naming)
CREATE TABLE department (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  creation_date DATE,
  head_employee_id BIGINT
);

CREATE TABLE employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  dob DATE,
  salary DOUBLE,
  address VARCHAR(500),
  role_title VARCHAR(255),
  joining_date DATE,
  yearly_bonus_percentage DOUBLE,
  manager_id BIGINT,
  department_id BIGINT
);

-- Foreign keys (added after tables exist to avoid circular DDL ordering issues)
ALTER TABLE employee
  ADD CONSTRAINT fk_emp_department FOREIGN KEY (department_id) REFERENCES department(id);

ALTER TABLE employee
  ADD CONSTRAINT fk_emp_manager FOREIGN KEY (manager_id) REFERENCES employee(id);

ALTER TABLE department
  ADD CONSTRAINT fk_dept_head FOREIGN KEY (head_employee_id) REFERENCES employee(id);
